from functools import reduce

# Even Fibonacci numbers

## Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

left = 1
right = 2
terms = [left, right]

while right < 4_000_000:
	sum = left+right
	left = right
	right = sum
	terms.append(sum)

even_terms = list(filter(lambda x: x % 2 == 0, terms))
terms_sum = reduce((lambda x, y: x + y), even_terms)

print(terms_sum)
#=> 4613732
