# Even Fibonacci numbers

## Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

max = 4_000_000
values = [1,2]

loop do
  new_value = values[-2] + values[-1]
  break if new_value > max
  values.push(new_value)
end

even_sum = values.select(&:even?).reduce(&:+)

even_sum #=> 4613732
