// Even Fibonacci numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import "fmt"

func main() {

	fibonaccis := []int{1, 2}
	sum := 0

	for fibonaccis[len(fibonaccis)-1] < 4000000 {
		fibonaccis = append(fibonaccis, fibonaccis[len(fibonaccis)-1]+fibonaccis[len(fibonaccis)-2])
	}

	for i := 0; i < len(fibonaccis); i++ {
		if fibonaccis[i]%2 == 0 {
			sum += fibonaccis[i]
		}
	}

	fmt.Println(sum) // 4613732
}
